### ISSUE TITLE
Keyboard Shortcuts window should close with Esc key

### ISSUE THREAD

**Issue by waldyrious** [elementary/shortcut-overlay#117]
### Problem

Currently it's possible to press the Super (aka Win) key to bring up the Keyboard Shortcuts window, and press the same key to hide it again.

### Proposal

It should be possible to use the Esc key to dismiss the Keyboard Shortcuts panel.

**Comment by cassidyjames** [comment]
@waldyrious that's currently implemented; is that not working for you?

https://github.com/elementary/shortcut-overlay/blob/4cb09d073ac65460719f951f7ef4207ff67f3e35/src/Application.vala#L39

**Comment by waldyrious** [comment]
Weird, I re-tested now and indeed Esc is working. I have no idea what caused the issue. Sorry for the noise! :sweat_smile:
