### ISSUE TITLE
Handle null shortcuts

### ISSUE THREAD

**Issue by danrabbit** [elementary/shortcut-overlay#12]
It looks like right now we just leave the right side blank which looks weird. We should either not show both the label and the shortcut widget or have some kind of disabled widget/text

**Comment by cassidyjames** [comment]
I like a disabled style; if we're explicitly choosing to put it in the shortcut window, it should be something we deem useful. If a user unsets it at one point, we still deem it useful and should remind them that it's something they can re-set.
