### ISSUE TITLE
Don't exit on focus-out when running from Terminal

### ISSUE THREAD

**Issue by danrabbit** [elementary/shortcut-overlay#13]
This would make development easier since we can use Inspector etc

**Comment by cassidyjames** [comment]
Would passing a command line argument be fine for this?

**Comment by danrabbit** [comment]
@cassidyjames Yeah but I figure any time we're running from Terminal we probably don't want to auto close :man_shrugging:

**Comment by cassidyjames** [comment]
@danrabbit is that something we can detect? :stuck_out_tongue: If not directly, we could also do the inverse: pass a flag for the auto-close behavior and use that command for the overlay key, so the command without the flag wouldn't have it.

…Unless we can just detect that it's being run from Terminal. But I don't know how that'd work.
