### ISSUE TITLE
Grab overlay keydown, and close on keyup

### ISSUE THREAD

**Issue by cassidyjames** [elementary/shortcut-overlay#18]
Apparently the overlay key unfocuses the window on keydown, then fires the event on keyup. This makes the shortcut overlay close and immediately reopen when the super key is pressed.

@danrabbit wondered if we could grab the overlay keydown (to make it not unfocus the window), then close the window on keyup. This would mean tapping the overlay key without the app open would open it, tapping it again would close it.

**Comment by danrabbit** [comment]
It looks like Gtk won't accept `<Super>` as an accelerator on its own. So the next thing to try is grabbing the key manually with gdk

**Comment by aroman** [comment]
How does slingshot handle this? It behaves correctly (toggles with repeated presses of the overlay key) if the overlay key is set to launch "Applications Menu" in switchboard. 

I was doing a bit of digging, and it seems like mutter is grabbing the keyboard when the overlay key is pressed and released:

```
/* We want to unfreeze events, but keep the grab so that if the user
* starts typing into the overlay we get all the keys */
```
(from [core/keybindings.c#2015](https://github.com/GNOME/mutter/blob/0332b7394e56f71c15692663ab05f8c84a4b9eff/src/core/keybindings.c#L2015))

AFAICT, grabbing keyboard input there means that it won't be delivered to other apps besides gala/mutter.

But it works for slingshot. So, is gala doing something special there?

**Comment by vkareh** [comment]
@danrabbit - GTK can parse `Super_L` as an accelerator, most likely your window manager is having issues with interpreting it. I added it in my fork (https://github.com/vkareh/shortcut-overlay/commit/fb0468f8ad1ca95916fe2e651c7eed21bf997cde) and did a preliminary run on Marco (MATE) - works perfectly fine. I'm in the process of setting up Juno on qemu to give it a go with Gala.

**Comment by vkareh** [comment]
oh okay, just installed it and I see the issue - it reopens as soon as it closes, probably due to window focus. You're using mutter to drive the initial keybinding, right? Might need to ungrab the key from it and focus on the current window. Or instead lock the input by doing a synchronous grab, like @aroman said, and then release it. I'll see if I have some cycles to play with this and submit a fix.

**Comment by danrabbit** [comment]
Yeah so I think the big difference between the applications menu and the shortcut overlay is that there's the hide on unfocus behavior. So when you press the super key again, the window loses focus and closes and then gets relaunched

**Comment by vkareh** [comment]
Okay, I submitted a small hack that fixes the issue on my side. I have not tested this extensively, but hopefully it will address user concerns in the meantime - the ideal fix, I think, is having the settings daemon make the distinction between `KeyPress` and `KeyRelease` depending on whether it's a modifier key or not, but that's a much larger change with the potential of breaking other things (and possibly needs changes to mutter directly).
