### ISSUE TITLE
Minimize key not included?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/shortcut-overlay#55]
The Minimize keyboard shortcut isn't shown, while it does exist. 
![screenshot from 2018-11-09 11 50 03 2x](https://user-images.githubusercontent.com/523210/48258596-bc560400-e415-11e8-8d94-480c0c1cc67d.png)
![screenshot from 2018-11-09 11 48 25](https://user-images.githubusercontent.com/523210/48258500-7ac55900-e415-11e8-88eb-de65f5fcc76b.png)

Code: https://github.com/elementary/shortcut-overlay/blob/master/src/Views/ShortcutsView.vala#L45-L52

**Comment by cassidyjames** [comment]
We're moving away from Minimize generally, so we decided not to include it in the new Shortcut Overlay.

**Comment by danrabbit** [comment]
Closing because of Cassidy's comment
