### ISSUE TITLE
The shortcut overlay icon appears on the dock only on exiting. 

### ISSUE THREAD

**Issue by Blast-City** [elementary/shortcut-overlay#67]
1- Press the Super key to see the shortcut overlay.
2- Press the Super key again or the Esc key to exit.

**Result:** The shortcut overlay icon appears on the dock for a brief moment after step 2.

I guess that the icon should appear on the dock as soon as your open the shortcut overlay and disappear when the overlay is not visible.

Closing the shortcut overlay with the window button doesn't make the dock icon appear.

P.S: I'm sorry if this is issue has already been reported.

**Comment by Blast-City** [comment]
![6](https://user-images.githubusercontent.com/33494283/56868259-0cd31500-69e8-11e9-81b0-c82135da0688.gif)

**Comment by danirabbit** [comment]
This seems to be fixed in OS 8
