### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by tetebueno** [elementary/shortcut-overlay#82]
"Dark mode" stopped working with one of the latest updates.

### To Reproduce
1. Press the `super` key.
2. Shortcuts overlay will display.

### Expected behavior
When "dark mode" is "enabled" (I used elementary-tweaks package to do so, that's the reason behind the quoting) the window used to be coherent with the rest of the applications.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/9064236/84545857-6a065480-acd6-11ea-802a-d9296f8dede8.png)
Note AppCenter respecting the dark theme behind.

## Platform Information
![image](https://user-images.githubusercontent.com/9064236/84546085-e1d47f00-acd6-11ea-8c61-892db6b1e657.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
This used to work before last update.

**Comment by ryonakano** [comment]
elementary OS does not currently support dark mode officially, but it will in the next version. In the latest version of this app, the support for official dark mode was adopted, and now it won't follow the unofficial dark style preference which you can now configurable in elementary Tweaks. When the next version of elementary OS is released, the app should follow the dark style preference selected in System Settings.
