### ISSUE TITLE
ERROR:  Dependency "libhandy-1" not found

### ISSUE THREAD

**Issue by a-plastic-bag** [elementary/shortcut-overlay#95]
## What Happened
On executing `meson build <source code> --prefix=/usr ` this error occurs:

`meson.build:23:0: ERROR:  Dependency "libhandy-1" not found, tried pkgconfig and cmake`

I'm unable to find libhandy-1 anywhere, and where I do find repositories that claim to have it, when i run `sudo apt install libhandy-1` it still returns `E: Unable to locate package libhandy-1`

## Expected Behavior
`meson build` runs without error.

## Steps to Reproduce

1. Install all dependencies
2. Run `meson build <source code> --prefix=/usr`

### Logs

`The Meson build system`
`Version: 0.49.2`
`Source dir: /home/<REDACTED>/Downloads/shortcut-overlay-master`
`Build dir: /home/<REDACTED>/build`
`Build type: native build`
`Project name: io.elementary.shortcut-overlay`
`Project version: 1.1.2`
`Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")`
`Native Vala compiler: valac (valac 0.40.25)`
`Build machine cpu family: x86_64`
`Build machine cpu: x86_64`
`Found pkg-config: /usr/bin/pkg-config (0.29.1)`
`Dependency glib-2.0 found: YES 2.56.4`
`Dependency gobject-2.0 found: YES 2.56.4`
`Dependency granite found: YES 5.5.0`
`Dependency gtk+-3.0 found: YES 3.22.30`
`Dependency gee-0.8 found: YES 0.20.2`
`Found CMake: /usr/bin/cmake (3.10.2)`
`Dependency libhandy-1 found: NO (tried pkgconfig and cmake)`

`meson.build:23:0: ERROR:  Dependency "libhandy-1" not found, tried pkgconfig and cmake`

`A full log can be found at /home/<REDACTED>/build/meson-logs/meson-log.txt`

## Platform Information

elementary OS 5.1.7 Hera
Built on Ubuntu 18.04.4 LTS
Linux 5.4.0-73-generic
GTK 3.22.30
Dual-Core Intel® Celeron® CPU  N3060  @ 1.60GHz
Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)
3.9 GB memory

**Comment by a-plastic-bag** [comment]
Okay I've found a copy of libhandy-1 but it requires libc6 >=2.29, however Elementary OS 5.1.7 Hera uses Ubuntu 18.04.4 LTS. Am i missing something?

**Comment by meisenzahl** [comment]
I am sorry, but the current version (`master`) is only compatible with elementary OS 6. The last version compatible with elementary OS 5.1.7 Hera is [1.1.2](https://github.com/elementary/shortcut-overlay/releases/tag/1.1.2).

**Comment by a-plastic-bag** [comment]
Oh ok. Thanks for replying.
